baseURL = "https://minhtrung0707.github.io/fcj-hugo-report/"
relativeURLs = true
canonifyURLs = false
defaultContentLanguage = "vi"

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = ""
  description = ""
  author = "Phan Nguyen Minh Trung"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false

# Tiêu đề chính của trang web bằng tiếng Việt
title = "Báo cáo thực tập tốt nghiệp"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true